apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <ECR-BACKEND-URL>
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: rds-secret
